export const translations: Record<string, any> = {
  it: {
    header: {
      howItWorks: "Come funziona"
    },
    hero: {
      title: "Trova il regalo che lascia il segno.",
      subtitle: "Descrivi il destinatario e lascia che la nostra Intelligenza Artificiale analizzi la sua personalità per suggerirti l'idea perfetta.",
      inputLabel: "Chi riceverà il regalo?",
      placeholder: "Es: Mia sorella di 25 anni, ama il trekking, la fotografia analogica e i gatti. Cerca qualcosa di originale per il suo compleanno.",
      budgetLabel: "Budget Massimo",
      button: "Trova il Regalo Ideale",
      loading: "Analisi in corso..."
    },
    results: {
      profileTitle: "Analisi Psicologica",
      profileSubtitle: "Il Profilo del Destinatario",
      seeOnAmazon: "Vedi su Amazon",
      copyLink: "Copia link",
      regenerate: "Mostrami altre 6 idee",
      trustTitle: "Perché fidarsi?",
      trustDesc: "I nostri suggerimenti sono generati analizzando migliaia di recensioni e tendenze di mercato per garantirti solo il meglio."
    },
    footer: {
      mission: "La missione di PerfectGift è semplificare la ricerca del regalo ideale, combinando psicologia e tecnologia per creare momenti indimenticabili.",
      quickLinks: "Link Rapidi",
      affiliation: "Affiliazione",
      affiliationDesc: "In qualità di Affiliato Amazon, riceviamo un guadagno dagli acquisti idonei. Questo non comporta alcun costo aggiuntivo per te.",
      rights: "Tutti i diritti riservati."
    },
    cookie: {
      banner: "Utilizziamo i cookie per personalizzare i contenuti e gli annunci, e per analizzare il nostro traffico. Condividiamo inoltre informazioni sul modo in cui utilizza il nostro sito con i nostri partner (Google e Amazon).",
      accept: "Accetta tutti",
      policy: "Cookie Policy"
    },
    seo: {
      title: "L'evoluzione del dono: Come l'Intelligenza Artificiale trasforma la scelta del regalo perfetto",
      p1: "Trovare idee regalo personalizzate è sempre stata una sfida...",
      h2: "Idee regalo personalizzate: Oltre il semplice oggetto",
      p2: "Quando ci chiediamo cosa regalare..."
    },
    legal: {
      privacyTitle: "Privacy Policy",
      cookieTitle: "Cookie Policy",
      backToHome: "Torna alla Home"
    },
    howItWorks: {
      title: "Come Funziona PerfectGift",
      subtitle: "Utilizziamo le tecnologie di intelligenza artificiale più avanzate per trasformare le tue parole nel regalo perfetto. Ecco il nostro processo in 4 semplici step.",
      step1Title: "Descrivi il Destinatario",
      step1Desc: "Inserisci una descrizione libera della persona. Più dettagli fornisci (età, hobby, stile di vita, sogni), più precisa sarà l'analisi dell'IA.",
      step2Title: "Imposta il Budget",
      step2Desc: "Definisci quanto vuoi spendere. L'algoritmo filtrerà le opzioni per garantirti il miglior rapporto qualità-prezzo entro i tuoi limiti.",
      step3Title: "Analisi Psicologica",
      step3Desc: "La nostra IA elabora i dati per creare un profilo psicologico del destinatario, identificando i suoi desideri latenti.",
      step4Title: "Ricevi i Suggerimenti",
      step4Desc: "Ottieni una lista di 6 idee regalo uniche, complete di motivazione e link diretto per l'acquisto su Amazon."
    }
  },
  en: {
    header: {
      howItWorks: "How it works"
    },
    hero: {
      title: "Find the gift that leaves a mark.",
      subtitle: "Describe the recipient and let our Artificial Intelligence analyze their personality to suggest the perfect idea.",
      inputLabel: "Who will receive the gift?",
      placeholder: "Ex: My 25-year-old sister, loves trekking, analog photography and cats. Looking for something original for her birthday.",
      budgetLabel: "Maximum Budget",
      button: "Find the Perfect Gift",
      loading: "Analyzing..."
    },
    results: {
      profileTitle: "Psychological Analysis",
      profileSubtitle: "Recipient Profile",
      seeOnAmazon: "View on Amazon",
      copyLink: "Copy link",
      regenerate: "Show me 6 more ideas",
      trustTitle: "Why trust us?",
      trustDesc: "Our suggestions are generated by analyzing thousands of reviews and market trends to guarantee you only the best."
    },
    footer: {
      mission: "PerfectGift's mission is to simplify the search for the ideal gift, combining psychology and technology to create unforgettable moments.",
      quickLinks: "Quick Links",
      affiliation: "Affiliation",
      affiliationDesc: "As an Amazon Associate, we earn from qualifying purchases. This does not involve any additional cost for you.",
      rights: "All rights reserved."
    },
    cookie: {
      banner: "We use cookies to personalize content and ads, and to analyze our traffic. We also share information about your use of our site with our partners (Google and Amazon).",
      accept: "Accept all",
      policy: "Cookie Policy"
    },
    seo: {
      title: "The Evolution of Gifting: How AI Transforms the Search for the Perfect Gift",
      p1: "Finding personalized gift ideas has always been a challenge...",
      h2: "Personalized Gift Ideas: Beyond the Simple Object",
      p2: "When we ask ourselves what to give..."
    },
    legal: {
      privacyTitle: "Privacy Policy",
      cookieTitle: "Cookie Policy",
      backToHome: "Back to Home"
    }
  },
  es: {
    header: { howItWorks: "Cómo funciona" },
    hero: {
      title: "Encuentra el regalo que deja huella.",
      subtitle: "Describe al destinatario y deja che nuestra Inteligencia Artificial analice su personalidad para sugerirte la idea perfetta.",
      inputLabel: "¿Quién recibirá el regalo?",
      placeholder: "Ej: Mi hermana de 25 años, ama el senderismo, la fotografía analógica y los gatos.",
      budgetLabel: "Presupuesto Máximo",
      button: "Encontrar el Regalo Perfecto",
      loading: "Analizando..."
    },
    results: {
      profileTitle: "Análisis Psicológico",
      profileSubtitle: "Perfil del Destinatario",
      seeOnAmazon: "Ver en Amazon",
      copyLink: "Copiar enlace",
      regenerate: "Muéstrame 6 ideas más",
      trustTitle: "¿Por qué confiar?",
      trustDesc: "Nuestras sugerencias se generan analizando miles de reseñas y tendencias del mercado."
    },
    footer: {
      mission: "La misión de PerfectGift es simplificar la búsqueda del regalo ideal.",
      quickLinks: "Enlaces Rápidos",
      affiliation: "Afiliación",
      affiliationDesc: "Como afiliados de Amazon, ganamos por compras elegibles.",
      rights: "Todos los derechos reservados."
    },
    cookie: {
      banner: "Utilizamos cookies para personalizar contenidos y anuncios.",
      accept: "Aceptar todo",
      policy: "Política de Cookies"
    },
    seo: {
      title: "La evolución del regalo",
      p1: "Encontrar ideas de regalos personalizados...",
      h2: "Ideas de regalos personalizados",
      p2: "Cuando nos preguntamos qué regalar..."
    },
    legal: {
      privacyTitle: "Política de Privacidad",
      cookieTitle: "Política de Cookies",
      backToHome: "Volver al inicio"
    }
  },
  fr: {
    header: { howItWorks: "Comment ça marche" },
    hero: {
      title: "Trouvez le cadeau qui marque les esprits.",
      subtitle: "Décrivez le destinataire et laissez notre Intelligence Artificielle analyser sa personnalité.",
      inputLabel: "Qui recevra le cadeau ?",
      placeholder: "Ex : Ma sœur de 25 ans, adore la randonnée, la photographie argentique et les chats.",
      budgetLabel: "Budget Maximum",
      button: "Trouver le Cadeau Idéal",
      loading: "Analyse en cours..."
    },
    results: {
      profileTitle: "Analyse Psychologique",
      profileSubtitle: "Profil du Destinataire",
      seeOnAmazon: "Voir sur Amazon",
      copyLink: "Copier le lien",
      regenerate: "Montrez-moi 6 autres idées",
      trustTitle: "Pourquoi nous faire confiance ?",
      trustDesc: "Nos suggestions sont générées en analysant des milliers d'avis et de tendances du marché."
    },
    footer: {
      mission: "La mission de PerfectGift est de simplifier la recherche du cadeau idéal.",
      quickLinks: "Liens Rapides",
      affiliation: "Affiliation",
      affiliationDesc: "En tant que partenaire Amazon, nous réalisons un bénéfice sur les achats remplissant les conditions requises.",
      rights: "Tous droits réservés."
    },
    cookie: {
      banner: "Nous utilisons des cookies pour personnaliser le contenu et les publicités.",
      accept: "Tout accepter",
      policy: "Politique relative aux cookies"
    },
    seo: {
      title: "L'évolution du cadeau",
      p1: "Trouver des idées de cadeaux personnalisés...",
      h2: "Idées de cadeaux personnalisés",
      p2: "Quand on se demande quoi offrir..."
    },
    legal: {
      privacyTitle: "Politique de Confidentialité",
      cookieTitle: "Politique relative aux Cookies",
      backToHome: "Retour à l'accueil"
    }
  },
  de: {
    header: { howItWorks: "Wie es funktioniert" },
    hero: {
      title: "Finden Sie das Geschenk, das Eindruck hinterlässt.",
      subtitle: "Beschreiben Sie den Empfänger und lassen Sie unsere Künstliche Intelligenz seine Persönlichkeit analysieren.",
      inputLabel: "Wer erhält das Geschenk?",
      placeholder: "Bsp: Meine 25-jährige Schwester, liebt Wandern, analoge Fotografie und Katzen.",
      budgetLabel: "Maximales Budget",
      button: "Das perfekte Geschenk finden",
      loading: "Analyse läuft..."
    },
    results: {
      profileTitle: "Psychologische Analyse",
      profileSubtitle: "Empfängerprofil",
      seeOnAmazon: "Auf Amazon ansehen",
      copyLink: "Link kopieren",
      regenerate: "Zeige mir 6 weitere Ideen",
      trustTitle: "Warum uns vertrauen?",
      trustDesc: "Unsere Vorschläge werden durch die Analyse von Tausenden von Bewertungen und Markttrends generiert."
    },
    footer: {
      mission: "Die Mission von PerfectGift ist es, die Suche nach dem idealen Geschenk zu vereinfachen.",
      quickLinks: "Schnelllinks",
      affiliation: "Affiliation",
      affiliationDesc: "Als Amazon-Partner verdienen wir an qualifizierten Verkäufen.",
      rights: "Alle Rechte vorbehalten."
    },
    cookie: {
      banner: "Wir verwenden Cookies, um Inhalte und Anzeigen zu personalisieren.",
      accept: "Alle akzeptieren",
      policy: "Cookie-Richtlinie"
    },
    seo: {
      title: "Die Entwicklung des Schenkens",
      p1: "Personalisierte Geschenkideen zu finden...",
      h2: "Personalisierte Geschenkideen",
      p2: "Wenn wir uns fragen, was wir schenken sollen..."
    },
    legal: {
      privacyTitle: "Datenschutzrichtlinie",
      cookieTitle: "Cookie-Richtlinie",
      backToHome: "Zurück zur Startseite"
    }
  }
};
